In [5]:
import pandas as pd

In [6]:
data=pd.read_csv("huge_1M_titanic.csv")

In [7]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [8]:
data.shape

(1000000, 12)

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [10]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [11]:
data=data.drop(columns=["PassengerId","Name","Age","Ticket","Cabin",])

In [12]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [13]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [14]:
data["Embarked"].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [15]:
data["Embarked"]=data["Embarked"].replace({"S": "Southampton", "C": "Cherbourg", "Q": "Queenstown"})

In [16]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165    Cherbourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416    Cherbourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769    Cherbourg

In [17]:
data.dropna(subset=["Embarked"], inplace=True)

In [18]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [19]:
data["Fare"]=data["Fare"].astype(int)

In [20]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76    Cherbourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12    Cherbourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4    Cherbourg

## feature encoding

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
label=LabelEncoder()

In [23]:
data["Sex"] = label.fit_transform(data["Sex"])

In [24]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76    Cherbourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12    Cherbourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4    Cherbourg

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
onehot=OneHotEncoder(sparse_output=False)

In [29]:
embarked=onehot.fit_transform(data[["Embarked"]])

In [32]:
embarked=pd.DataFrame(embarked, columns=onehot.get_feature_names_out(["Embarked"]))

In [34]:
embarked

        Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                      1.0                  0.0                   0.0
1                      0.0                  0.0                   1.0
2                      1.0                  0.0                   0.0
3                      0.0                  0.0                   1.0
4                      1.0                  0.0                   0.0
...                    ...                  ...                   ...
997755                 0.0                  0.0                   1.0
997756                 0.0                  0.0                   1.0
997757                 0.0                  0.0                   1.0
997758                 0.0                  0.0                   1.0
997759                 0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [36]:
data=pd.concat([data.drop(columns=["Embarked"]), embarked], axis=1)

In [37]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

## feature scalling

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
scaler=StandardScaler()

In [40]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Cherbourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [41]:
num_cols=['Pclass', 'SibSp', 'Parch', 'Fare']

In [42]:
data[num_cols]=scaler.fit_transform(data[num_cols])

In [43]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,0.896610,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.479488,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.437788,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.416938,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.604587,1.0,0.0,0.0

In [44]:
data.isnull().sum()

Survived                2234
Pclass                  2234
Sex                     2234
SibSp                   2234
Parch                   2234
Fare                    2234
Embarked_Cherbourg      2234
Embarked_Queenstown     2234
Embarked_Southampton    2234
dtype: int64

In [45]:
data=data.dropna()

In [46]:
data.dropna(inplace=True)

In [47]:
import pickle

In [ ]:
with open("label.pkl", "wb") as f:
    pickle.dump(label, f)

In [48]:
with open("onehot.pkl", "wb") as f:
    pickle.dump(onehot, f)

In [49]:
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

In [ ]:
X=data.drop(columns=["Survived"])

In [ ]:
y=data["Survived"]

In [ ]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

## train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=20,random_state=42)

In [ ]:
X_train , X_valid, y_train , y_valid= train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
data.shape

(995526, 9)

In [ ]:
X_train.shape

(796420, 8)

In [ ]:
X_valid.shape

(199106, 8)

In [ ]:
X_train.isnull().sum()

Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Cherbourg      0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [ ]:
import tensorflow

## model building

In [ ]:
(X_train.shape[1],)

(8,)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
model = Sequential([
    Dense(units=128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(units=64, activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=16, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

c:\Users\user\Desktop\naveen\ANN model\venv\Lib\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,033 (47.00 KB)

 Trainable params: 12,033 (47.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.optimizers import Adam

In [ ]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
EarlyStop=EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [ ]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=10, batch_size=32, callbacks=[EarlyStop])

Epoch 1/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 55s 2ms/step - accuracy: 0.8496 - loss: 0.3416 - val_accuracy: 0.8534 - val_loss: 0.3290
Epoch 2/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 52s 2ms/step - accuracy: 0.8557 - loss: 0.3274 - val_accuracy: 0.8541 - val_loss: 0.3261
Epoch 3/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 52s 2ms/step - accuracy: 0.8568 - loss: 0.3248 - val_accuracy: 0.8557 - val_loss: 0.3243
Epoch 4/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 51s 2ms/step - accuracy: 0.8571 - loss: 0.3236 - val_accuracy: 0.8559 - val_loss: 0.3257
Epoch 5/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 52s 2ms/step - accuracy: 0.8573 - loss: 0.3230 - val_accuracy: 0.8560 - val_loss: 0.3240
Epoch 6/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 51s 2ms/step - accuracy: 0.8575 - loss: 0.3225 - val_accuracy: 0.8558 - val_loss: 0.3232
Epoch 7/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 444s 18ms/step - accuracy: 0.8576 - loss: 0.3221 - val_accuracy: 0.8560 - val_loss: 0.3228
Epoch 8/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 51s 2ms/step - accuracy: 0.8578 - loss: 0.3219 - val_accuracy: 0.8562 - val_loss: 0.3230
Epoch 9/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 50s 2ms/step - accuracy: 0.8579 - loss: 0.3218 - val_accuracy: 0.8562 - val_loss: 0.3233
Epoch 10/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 54s 2ms/step - accuracy: 0.8579 - loss: 0.3216 - val_accuracy: 0.8564 - val_loss: 0.3225

In [ ]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.