In [2]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [3]:
with open("label.pkl", "rb") as file:
    label = pickle.load(file)

In [65]:
with open("onehot.pkl", "rb") as file:
    onehot = pickle.load(file)

In [54]:
with open("scaler.pkl", "rb") as file:
    scaler = pickle.load(file)

In [6]:
model=load_model("model.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [93]:
user={"Pclass":1,"Sex":"female","SibSp":0,"Parch":0,"Fare":76,"Embarked":"Cherbourg"}

In [94]:
user=pd.DataFrame([user])

In [95]:
user

   Pclass     Sex  SibSp  Parch  Fare   Embarked
0       1  female      0      0    76  Cherbourg

In [96]:
user["Sex"]=label.transform(user["Sex"])

In [97]:
user

   Pclass  Sex  SibSp  Parch  Fare   Embarked
0       1    0      0      0    76  Cherbourg

In [98]:
embarked=onehot.transform(user[["Embarked"]])

In [99]:
embarked = pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [100]:
embarked

   Embarked_Cherbourg  Embarked_Queenstown  Embarked_Southampton
0                 1.0                  0.0                   0.0

In [101]:
user = pd.concat(
    [user.drop(columns=["Embarked"]), embarked],
    axis=1)

In [102]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,0,0,0,76,1.0,0.0,0.0

In [103]:
user[['Pclass', 'SibSp', 'Parch', 'Fare']]=scaler.transform(user[['Pclass', 'SibSp', 'Parch', 'Fare']])

In [104]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0,-0.462644,-0.469267,0.89661,1.0,0.0,0.0

In [105]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step

In [106]:
y=y[0][0]

In [107]:
y

np.float32(0.985954)

In [108]:
if y>0.5:
    print("Survived")
else:
    print("Not Survived")

Survived